services:
  - type: web
    name: folushovictory-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: RESEND_API_KEY
        fromGroup: fvs-secrets
      - key: RESEND_FROM_EMAIL
        fromGroup: fvs-secrets

