services:
  - type: web
    name: folushovictory-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: fvs-secrets

